# Build stage
FROM node:16-alpine as build

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage
FROM nginx:alpine

# Copy built files and config
COPY --from=build /app/build /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

# Copy and make startup script executable
COPY start.sh .
RUN chmod +x ./start.sh

EXPOSE 80

# # Use startup script
# CMD ["./start.sh"]
