# Development configuration
version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: twohun
      POSTGRES_PASSWORD: twohun_password
      POSTGRES_DB: twohun_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://twohun:twohun_password@db/twohun_db
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: 