name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Railway
        run: npm i -g @railway/cli@3.14.0
        
      - name: Deploy Services
        run: |
          # Deploy PostgreSQL first
          cd backend
          railway link --project-id ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service postgresql
          
          # Get PostgreSQL URL and set it for API
          DB_URL=$(railway variables -k | grep DATABASE_URL)
          railway variables -kv DATABASE_URL="$DB_URL" --service twohun
          
          # Deploy API
          railway up --service twohun
          
          # Get API URL and set it for frontend
          API_URL=$(railway variables -k | grep SERVICE_URL --service twohun)
          cd ../frontend
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway variables -kv REACT_APP_API_URL="$API_URL" --service frontend
          railway up --service frontend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 
