name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Railway
        run: npm i -g @railway/cli@3.14.0
        
      - name: Deploy Services
        run: |
          # Deploy Backend
          cd backend
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service postgresql
          railway up --service api
          
          # Deploy Frontend
          cd ../frontend
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --service frontend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 
